spring.application.name=reviewservice
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db?currentSchema=hotel_reviews
spring.datasource.username=natalija
spring.datasource.password=moja_lozinka
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.liquibase-schema=public
spring.liquibase.database-change-log-table=databasechangelog_reviews
spring.liquibase.database-change-log-lock-table=databasechangeloglock_reviews

hotel.app.jwtSecret=mySecretKeyForHotelAppMicroservicesThesis2025
hotel.app.jwtExpirationMs=86400000

spring.mvc.throw-exception-if-no-handler-found=true
spring.jackson.deserialization.fail-on-unknown-properties=true

spring.profiles.active=rest

services.reservation-service.url=http://localhost:8083